<?php

/**
 *@file
 *This module connects to the uPay Gateway and stores information about the donators in the database.
 */
 
/**
 *Implementation of hook_menu().
 */
 
function rmw_donations_menu() {
  $items = array();
  
  $items['donate'] = array(
    'title' => 'Regenerative Medicine Workshop Donations',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rmw_donations_form1'),
    'type' => MENU_NORMAL_ITEM,
  );
}

/**
 * Define the form that collects transaction information.
 */
function rmw_donations_form(){
  $form['first_name'] = array(
    '#title' => t('First Name'),
    '#type' => 'textfield',
    '#description' => t('Please enter your first name.'),
  );
   $form['last_name'] = array(
    '#title' => t('Last Name'),
    '#type' => 'textfield',
    '#description' => t('Please enter your last name.'),
  );
  $form['email'] = array(
    '#title' => t('Email address'),
    '#type' => 'textfield',
    '#description' => t('Please enter your email address.'),
  );
  $form['#submit'][] = 'rmwd_create_node_submit_function';
  $form['#submit'][] = 'rmwd_post_upay_submit_function';
  return $form;
}

function rmw_create_node_submit_function($form,&$form_state){
  // first name  = $form_state['first_name'];
  // last name   = $form_state['last_name'];
  // email address = $form_state['email'];

  $record = new stdClass();
  $record->first_name = $form_state['values']['first_name'];
  $record->last_name = $form_state['values']['last_name'];
  $record->email = $form_state['values']['email'];

  $table = 'rmw_donations'  

  drupal_write_record($table, $record);

  $form_state['rmw_donations']['tid'] = $record->tid;
}
